version: "3.2"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.81.1
    env_file: ./docker.env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    restart: always

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 3000:8080

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    restart: always


  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'
    restart: always

  # nginx:
  #   image: nginx:latest
  #   container_name: production_nginx
  #   volumes:
  #     - nginx-config:/etc/nginx/sites-enabled/default
  #   ports:
  #     - 8080:8080
  #     - 443:443

volumes:
  storage-data:
  database-data:
